 # source root
source_root: /data/FSMR_data/top_data/test/91-3003CN5S/        # target root
target_root: /data/FSMR_data/top_data/train/81FyMPk-WIS/
output_name: debugging_sanity_check.mp4
output_folder: video
checkpoint_path: /data/FSMR_data/checkpoint_fsmt/
name: ubc_checkpoints                           # name of checkpoint
finetune_sample: 300

batchsize: 3
epochs: 1
finetune_coor_step: 10                  # steps of finetuning geometry generator
lr: 0.0002                              # learning rate of finetuning geometry generator
lr_T: 0.005                             # learning rate of finetuning embedding of texture
lr_milestone:                           # steps of learning rate decay
  - 150

phase: finetune
background: background.png
pretrain_name:  latest_UBC_crop

resize: 256                             # size of image/pose
texture_size: 128                       # size of texture
hflip: false
URange: 256
VRange: 256

display: True
display_freq: 1

body_nc: 26

G:
  nf: 32                                # number of base filters in the generator
  n_res_blks: 5                         # number of residual blocks in content encoder/decoder
  nf_mlp: 256                           # number of base filters in MLP module
  latent_dim: 64                        # dimension of the latent code for the class model
  n_mlp_blks: 3                         # number of mlp blocks
  n_downs_content: 4                    # number of downsampling layers in content encoder
  n_downs_class: 4                      # number of downsampling layers in class model encoder
  input_dim: 26

Texture_G:
  nf: 64                                # number of base filters in the generator
  n_res_blks: 6                         # number of residual blocks in content encoder/decoder
  n_downs: 3                            # number of downsampling layers in content encoder
  input_dim: 72
  output_dim: 72

num_texture: 3

#Constraint
l_texture: 2.
l_coordinate: 5.0
l_mask: 0.5
l_vgg: 0.5
l_background: 0.4
